# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hospital.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "hospital.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ehospital.proto"y\n\x0b\x41ppointment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cpatient_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64octor_name\x18\x03 \x01(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x11\n\ttime_slot\x18\x06 \x01(\t""\n\x14\x41ppointmentIDRequest\x12\n\n\x02id\x18\x01 \x01(\x05"&\n\x0ePatientRequest\x12\x14\n\x0cpatient_name\x18\x01 \x01(\t"5\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"5\n\x0f\x41ppointmentList\x12"\n\x0c\x61ppointments\x18\x01 \x03(\x0b\x32\x0c.Appointment2\xed\x01\n\x0fHospitalService\x12\x33\n\x0f\x42ookAppointment\x12\x0c.Appointment\x1a\x12.OperationResponse\x12\x30\n\tQueryByID\x12\x15.AppointmentIDRequest\x1a\x0c.Appointment\x12\x33\n\x0eQueryByPatient\x12\x0f.PatientRequest\x1a\x10.AppointmentList\x12>\n\x11\x43\x61ncelAppointment\x12\x15.AppointmentIDRequest\x1a\x12.OperationResponseB\'\n\x14\x63om.example.hospitalB\rHospitalProtoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hospital_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\024com.example.hospitalB\rHospitalProtoP\001"
    _globals["_APPOINTMENT"]._serialized_start = 18
    _globals["_APPOINTMENT"]._serialized_end = 139
    _globals["_APPOINTMENTIDREQUEST"]._serialized_start = 141
    _globals["_APPOINTMENTIDREQUEST"]._serialized_end = 175
    _globals["_PATIENTREQUEST"]._serialized_start = 177
    _globals["_PATIENTREQUEST"]._serialized_end = 215
    _globals["_OPERATIONRESPONSE"]._serialized_start = 217
    _globals["_OPERATIONRESPONSE"]._serialized_end = 270
    _globals["_APPOINTMENTLIST"]._serialized_start = 272
    _globals["_APPOINTMENTLIST"]._serialized_end = 325
    _globals["_HOSPITALSERVICE"]._serialized_start = 328
    _globals["_HOSPITALSERVICE"]._serialized_end = 565
# @@protoc_insertion_point(module_scope)
